### ISSUE TITLE
Can't work with secrets

### ISSUE THREAD

**Issue by cglacet** [pytest-docker-compose/pytest-docker-compose#47]
I'm using secrets in my docker-compose file, I have something that looks like this: 

```yaml
# docker-compose.yml
version: '3.7'

secrets:
  DATABASE_URL:
    file: .secrets/db_url

services:
  app:
    build: .
    env_file:
     - .env
    environment:
      - TESTING=${TESTING:-False}
    secrets:
      - DATABASE_URL
```

I have a *settings.py* file that is responsible for loading secrets and environment variables into constants. Concerning the secrets part, it looks like so: 

```python
# secrets.py
import os

docker_security_folder = '/run/secrets/'

def read(secret_name):
  docker_security_file = os.path.join(docker_security_folder, secret_name)
  with open(docker_security_file) as f:
            return f.read().strip()
```

When I run `docker-compose` everything goes just fine and every call to `secrets.read('DATABASE_URL')` returns the expected URL. On the other hand, when I run pytest with docker-compose plugin I have the following error on `secrets.read('DATABASE_URL')`: 

```bash
error [Errno 2] No such file or directory: '/run/secrets/DATABASE_URL'
``` 

If I use environment variables it goes just fine in both cases. What is strange is that the `server_app` container seems to contain the right volumes even when ran from `pytest`:

```bash
$ docker container exec $(docker ps --filter name=server_app -q) cat /run/secrets/DATABASE_URL
postgresql+psycopg2://usr:pwd@host:5432/db
```

What is the problem, am I doing something wrong here? Thanks for your help!
